// Generated by CoffeeScript 1.6.3
(function() {
  var handlebars;

  handlebars = require("handlebars");

  handlebars.registerHelper("helperMissing", function() {
    return "missing helper";
  });

  handlebars.registerHelper("equals", function(a, b, options) {
    if ((a != null ? a.toString() : void 0) === (b != null ? b.toString() : void 0)) {
      return options.fn(this);
    } else {
      return options.inverse(this);
    }
  });

  handlebars.registerHelper("gt", function(a, b, options) {
    if (parseFloat(a) > parseFloat(b)) {
      return options.fn(this);
    } else {
      return options.inverse(this);
    }
  });

  handlebars.registerHelper("and", function(a, b, options) {
    if ((a != null) && (b != null)) {
      return options.fn(this);
    } else {
      return options.inverse(this);
    }
  });

  handlebars.registerHelper("neither", function(a, b, options) {
    if (!a && !b) {
      return options.fn(this);
    } else {
      return options.inverse(this);
    }
  });

  handlebars.registerHelper("mod", function(a, b, options) {
    if ((a + 1) % b !== 0) {
      return options.inverse(this);
    } else {
      return options.fn(this);
    }
  });

  handlebars.registerHelper("pp", function(options) {
    return JSON.stringify(this);
  });

  handlebars.registerHelper("size", function(a, options) {
    if (a === void 0) {
      return 0;
    }
    if (a.length) {
      if (_.isFunction(a.length)) {
        return a.length();
      } else {
        return a.length;
      }
    }
    if (a.size) {
      if (_.isFunction(a.size)) {
        return a.size();
      } else {
        return a.size;
      }
    }
    return 0;
  });

}).call(this);
