// Generated by CoffeeScript 1.6.3
(function() {
  var handlebars;

  handlebars = require("handlebars");

  handlebars.registerHelper("equals", function(a, b, options) {
    if ((a != null ? a.toString() : void 0) === (b != null ? b.toString() : void 0)) {
      return options.fn(this);
    } else {
      return options.inverse(this);
    }
  });

}).call(this);
