// Generated by CoffeeScript 1.6.3
(function() {
  var dataProvider, handlebars, render, _;

  render = require("./render");

  handlebars = require("handlebars");

  _ = require("lodash");

  dataProvider = require("../data_provider");

  handlebars.registerHelper("inject", function(path, options) {
    var compData, dataResult, tempContext;
    tempContext = _.clone(this);
    if (options.fn) {
      compData = JSON.parse(options.fn());
      _.assign(tempContext, compData);
    }
    dataResult = dataProvider.getCompData(path, tempContext);
    if (dataResult.found) {
      tempContext["_DATA_"] = dataResult.result;
    }
    return new handlebars.SafeString(render.renderComponent(path, tempContext));
  });

  handlebars.registerHelper("component", function(className, options) {
    return new handlebars.SafeString("<div class=\"" + className + "\" data-comp-path=\"" + this[render.CONST.COMP_PATH] + "\">" + (options.fn(this)) + "</div>");
  });

  handlebars.registerHelper("designPart", function(key, options) {
    return options.fn(this);
  });

}).call(this);
