// Generated by CoffeeScript 1.6.3
(function() {
  var handlebars, render, _;

  render = require("./render");

  handlebars = require("handlebars");

  _ = require("lodash");

  handlebars.registerHelper("inject", function(path, options) {
    debugger;
    var compData, tempContext;
    tempContext = _.clone(this);
    if (options.fn) {
      compData = JSON.parse(options.fn());
      _.assign(tempContext, compData);
    }
    return new handlebars.SafeString(render.renderComponent(path, tempContext));
  });

  handlebars.registerHelper("component", function(className, options) {
    return new handlebars.SafeString("<div class=\"" + className + "\" data-comp-path=\"" + this[render.CONST.COMP_PATH] + "\">" + (options.fn()) + "</div>");
  });

}).call(this);
