// Generated by CoffeeScript 1.6.3
(function() {
  var async, render;

  render = require("./render");

  async = require("./async");

  async.registerAsyncHelper("inject", function(path, options, resolve) {
    return render.renderComponent(path, this, resolve);
  });

}).call(this);
