// Generated by CoffeeScript 1.6.3
(function() {
  var blankTemplate, fs, handlebars, utils;

  fs = require("fs");

  handlebars = require("handlebars");

  utils = require("../utils");

  blankTemplate = handlebars.compile("");

  module.exports = {
    fromPath: function(path, callback) {
      var e, t, template;
      try {
        template = fs.readFileSync(path, {
          encoding: "utf-8"
        });
        t = handlebars.compile(template);
      } catch (_error) {
        e = _error;
        console.error("get and compile template from path " + path + " error", e);
        callback(e);
        return;
      }
      return callback(null, t);
    },
    fromText: function(text) {
      var err;
      try {
        return handlebars.compile(text);
      } catch (_error) {
        err = _error;
        console.error("compile template from text error", err);
        return "";
      }
    }
  };

}).call(this);
