// Generated by CoffeeScript 1.6.3
(function() {
  var blankTemplate, env, fs, handlebars, pathCache, textCache, utils;

  fs = require("fs");

  handlebars = require("handlebars");

  env = require("../enviroments");

  utils = require("../utils");

  pathCache = {};

  textCache = {};

  blankTemplate = handlebars.compile("");

  module.exports = {
    fromPath: function(path, callback) {
      var t;
      if (env.cache && (t = pathCache[path])) {
        callback(void 0, t);
        return;
      }
      return fs.readFile(path, function(err, data) {
        if (err) {
          console.error("open file " + path + " error", err);
          return callback(err);
        } else {
          t = handlebars.compile(data.toString());
          if (env.cache) {
            pathCache[path] = t;
          }
          return callback(void 0, t);
        }
      });
    },
    fromText: function(text) {
      var md5, t;
      if (env.cache) {
        md5 = utils.md5(text);
        if (t = textCache[md5]) {
          return t;
        }
      }
      t = handlebars.compile(text);
      if (env.cache) {
        textCache[md5] = t;
      }
      return t;
    }
  };

}).call(this);
