// Generated by CoffeeScript 1.6.3
(function() {
  var data, dataFilePath, env, fs, path, watch, _;

  fs = require("fs");

  path = require("path");

  watch = require("node-watch");

  env = require("./enviroments");

  _ = require("lodash");

  dataFilePath = env.dataFile;

  data = {};

  if (fs.existsSync(dataFilePath)) {
    data = require(dataFilePath);
  }

  watch(dataFilePath, function() {
    require.cache[dataFilePath] = null;
    data = require(dataFilePath);
    return console.log("[Data Reload]");
  });

  module.exports = {
    get: function(path, params) {
      var result;
      if (!_.has(data, path)) {
        return {
          found: false
        };
      }
      result = data[path];
      return {
        found: true,
        result: _.isFunction(result) ? result(params) : result
      };
    }
  };

}).call(this);
