// Generated by CoffeeScript 1.6.3
(function() {
  var config, configFile, cwdPath, env, envConfig, fs, outerConfig, path, _, _ref;

  fs = require("fs");

  path = require("path");

  _ = require("lodash");

  env = process.env.NODE_ENV || "dev";

  config = {
    serverPort: 8080,
    filesHome: "public",
    viewsHome: "public/views",
    componentsHome: "public/components",
    extraHelpers: []
  };

  cwdPath = process.cwd();

  configFile = path.resolve(cwdPath, "jiggly.json");

  if (fs.existsSync(configFile)) {
    outerConfig = require(configFile);
    _.assign(config, outerConfig);
    delete config.env;
    if (envConfig = (_ref = outerConfig.env) != null ? _ref[env] : void 0) {
      _.assign(config, envConfig);
    }
  }

  config.filesHome = path.resolve(cwdPath, config.filesHome);

  config.viewsHome = path.resolve(cwdPath, config.viewsHome);

  config.componentsHome = path.resolve(cwdPath, config.componentsHome);

  config.extraHelpers = _.map(config.extraHelpers, function(helperFile) {
    return path.resolve(cwdPath, helperFile);
  });

  console.log("Config loaded:");

  console.log(config);

  module.exports = config;

}).call(this);
