// Generated by CoffeeScript 1.6.3
(function() {
  var app, env, express, render;

  env = require("./enviroments");

  render = require("./handlebars/render");

  express = require("express");

  app = express();

  app.get(/^([^\.]+)$/, function(req, res) {
    var path;
    path = req.params[0];
    return render.renderFile(path, req.query, function(err, result) {
      if (err) {
        return res.send(500, {
          error: "render failed: \n" + err
        });
      } else {
        return res.send(result);
      }
    });
  });

  app.get(/^(.+)$/, function(req, res) {
    var path;
    path = req.params[0];
    return res.sendfile("" + env.filesHome + path);
  });

  app.listen(env.serverPort);

  console.log("server listening at port: " + env.serverPort);

}).call(this);
