// Generated by CoffeeScript 1.6.3
(function() {
  var crypto;

  crypto = require("crypto");

  module.exports = {
    syncLike: function(fs) {
      var i, nextList, _i, _ref;
      if (fs === void 0 || fs.length === 0) {
        return;
      }
      if (fs.length === 1) {
        return fs[0]();
      }
      nextList = [];
      for (i = _i = _ref = fs.length - 1; _ref <= 0 ? _i <= 0 : _i >= 0; i = _ref <= 0 ? ++_i : --_i) {
        if (i === fs.length - 1) {
          nextList[i] = void 0;
        } else {
          (function() {
            var index;
            index = i;
            return nextList[index] = function() {
              [].push.call(arguments, nextList[index + 1]);
              return fs[index + 1].apply(void 0, arguments);
            };
          })();
        }
      }
      return fs[0].call(void 0, nextList[0]);
    },
    md5: function(content) {
      return crypto.createHash("md5").update(content).digest("hex");
    },
    homePath: function() {
      return process.env[process.platform === "win32" ? "USERPROFILE" : "HOME"];
    }
  };

}).call(this);
